name: Create production site

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build and deploy 11ty to gh-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build 11ty
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true

      - name: Release the site
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
